### ISSUE TITLE
Mouseover / Clicks

### ISSUE THREAD

**Issue by potatoqualitee** [dataplat/dataplat.github.io#4]
* the link "steals" the mouse and makes it feel unclickable. can that behavior be the normal behavior of a click? generally the finger point
* also, if it's possible to automatically go to the Top once a link on the side has been clicked
right now, you gotta click then scroll back up if you click one down towards the bottom

**Comment by niphlod** [comment]
- we can make it `a` link rather than a `div`, no biggie
- we can, I didn't account for people not restricting the list on the left via search before clicking. To be fair, there was a scroll-to-top builtin for previous incarnations of this page but it has not been reactivated so it's just a matter of reenabling it, no biggie either

**Comment by niphlod** [comment]
clicks done

**Comment by niphlod** [comment]
also, scroll to top

**Comment by potatoqualitee** [comment]
👍 👍 👍 👍
